language: node_js
node_js:
- iojs
- '0.10'
- '0.12'
before_script:
- npm install -g istanbul
- npm install -g mocha
- npm install -g coveralls
after_script:
- npm run coverage
- npm run coveralls
notifications:
  slack:
    secure: Cp2hwUNfqgw2OMjI936aXOYdPKrVjTZ4mEj8y/UUdcv4PiJgOfqYOQBPddxxJCOAA33d1iMA2bDsSx+oI8mOX+uMMhC478Cqq5YlfsXlEtPOmQhKFeGvIrduxLSzL1cAYs8/h+DPppjBG2y/Qg4uPP4MjrvzitObZOZZeGtPNBxvsfXAiteF4+iZSGj2oaq+ULH3y8fWbX91f9SfJNF9rRhHe9DiHNd28R5+yxa80mYxmJpfpVw6bzr+aMHeG6bnMdf8rJ6Fbwu0CLzn85WzR/2daUEYUmY5yw1ToZOIwzSLLzSaLCEpG0j324McZ+qeAAdLXEfpQwpGqd1tg667MbdnCBf74eTSzA037rz40dsep7Vx5rmcalNc75nFVxQkWOZzdJw1jh3I9jv3/Z5p712Jt1edSCTyqfcJ1O3Bv+AoptgzEY79hcIT6v2Wb/bO5AsYtEaIqfk6na1dDMSGI0xz98zm6d87Qoe24gWOme64K/Fgt39HU5+mJGUDC/Ukl1mj7AUaMIH8M0Y6Mgy5Q5hH7P7+HDncXsxWqj7mqbuEK6MpwfDJCcyhrUYB47xMy4ELYSuFGS+1C8LoN90gGmmyWOAa9cW6Vxzu+pVoB9CRuX1JLeCYxeYkTY0FcYjKwvSQT2Bvq5zqgkDIWI2btF/lCOF8+m/T7K89lp0hbsY=
